[package]
org = "ministry"
name = "library_service"
version = "1.0.0"
distribution = "2201.13.5"

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
artifactId = "mysql-connector-j"
version = "8.4.0"
groupId = "com.mysql"
